name: dart_shelf
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

dependencies:
  args: ^2.4.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path: ^1.9.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  path: any
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
